name: Update README with Config Files

on:
  push:
    paths:
      - '.gitconfig.example'
      - '.gitconfig-github'
      - '.gitconfig-gitlab'
      - '.github/workflows/update-readme.yml'

jobs:
  code_embedder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: kvankova/code-embedder@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
